# Generated by Django 5.1.4 on 2025-02-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_track_url_track_s3_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='featuring_artists',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
