version: "3"

services:
  frontend:
    container_name: beow_frontend
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/client
      - /client/node_modules
