version: "3"

services:
  frontend:
    container_name: beow_frontend
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "1207:1207"
    volumes:
      - ./client:/client # bind mount
      - node_modules:/client/node_modules # docker-managed volume
  backend:
    container_name: beow_backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "2808:2808"
  
volumes:
  node_modules:
